# See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
lowercaseOutputName: true
rules:
  # OAuth Metrics
  # WARNING: Make sure that the ordering of the attributes is the same as in MBean names
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+), (.+)=(.+), (.+)=(.+)><>(count|totalTimeMs):"
    name: "strimzi_oauth_$1_$12"
    type: COUNTER
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
      "$8": "$9"
      "$10": "$11"
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+), (.+)=(.+)><>(count|totalTimeMs):"
    name: "strimzi_oauth_$1_$10"
    type: COUNTER
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
      "$8": "$9"
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+)><>(count|totalTimeMs):"
    name: "strimzi_oauth_$1_$8"
    type: COUNTER
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+), (.+)=(.+), (.+)=(.+)><>(.+):"
    name: "strimzi_oauth_$1_$12"
    type: GAUGE
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
      "$8": "$9"
      "$10": "$11"
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+), (.+)=(.+)><>(.+):"
    name: "strimzi_oauth_$1_$10"
    type: GAUGE
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
      "$8": "$9"
  - pattern: "strimzi.oauth<type=(.+), context=(.+), kind=(.+), host=\"(.+)\", path=\"(.+)\", (.+)=(.+)><>(.+):"
    name: "strimzi_oauth_$1_$8"
    type: GAUGE
    labels:
      context: "$2"
      kind: "$3"
      host: "$4"
      path: "$5"
      "$6": "$7"
