apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: oauth
          introspectionEndpointUri: http://spring:8080/oauth/check_token
          clientId: kafka
          clientSecret:
            secretName: my-cluster-kafka-client-secret
            key: secret
          checkIssuer: false
          accessTokenIsJwt: false
          userNameClaim: user_name
          fallbackUserNameClaim: client_id
          fallbackUserNamePrefix: client-account-
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

